### ISSUE TITLE
nfc-list.exe was compiled for debug in v1.6.8421.33645

### ISSUE THREAD

**Issue by radorodopski** [xavave/Mifare-Windows-Tool#64] opened 2023-01-21 22:51 UTC
nfc-list.exe was compiled for debug and looks for ucrtbase**d**.dll and VCRUNTIME140**D**.dll

Could you please re-compile the executable (and check if any other were compiled for debug by mistake as well) and fix the last release?

Thanks!

![image](https://user-images.githubusercontent.com/2711709/213890147-59fbcf68-64fb-4a99-a583-682f22d747e5.png)
![image](https://user-images.githubusercontent.com/2711709/213890159-2d91c5dc-95ad-4f8c-b2c4-bd08ebbb6405.png)

**Comment by xavave** [comment] 2023-01-22 19:09
Hi, this should be fixed now: https://github.com/xavave/Mifare-Windows-Tool/releases/latest

**Closed by xavave** 2023-01-22 19:09 UTC

**Comment by radorodopski** [comment] 2023-01-22 19:22
No, still one more issue (I tried to write tag):

![image](https://user-images.githubusercontent.com/2711709/213935648-354847cb-bf22-44c7-aa34-5e41aa8e69e7.png)

**Comment by xavave** [comment] 2023-01-22 19:26
Which windows version do you have ?
Can you delete file winsdcard.dll in MWT installation folder ?
C:\program files (x86)\mifarewindowstool\nfctools_pcsc\

Did you use mifare windows tool before this version ? If so, did you I uninstall libUsbK driver filter ?

**Comment by xavave** [comment] 2023-01-22 19:44
> nfc-list.exe was compiled for debug and looks for ucrtbase**d**.dll and VCRUNTIME140**D**.dll
> 
> 
> 
> Could you please re-compile the executable (and check if any other were compiled for debug by mistake as well) and fix the last release?
> 
> 
> 
> Thanks!
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/2711709/213890147-59fbcf68-64fb-4a99-a583-682f22d747e5.png)
> 
> ![image](https://user-images.githubusercontent.com/2711709/213890159-2d91c5dc-95ad-4f8c-b2c4-bd08ebbb6405.png)
> 
> 
> 
> 

I compiled in release mode , maybe I forgot something in Cmake settings

**Comment by xavave** [comment] 2023-01-22 19:55
> Which windows version do you have ?
> Can you delete file winscard.dll in MWT installation folder ?
> C:\program files (x86)\mifarewindowstool\nfctools_pcsc\
> (So windows will use its default version)
> Did you use mifare windows tool before this version ? If so, did you I uninstall libUsbK driver filter ?

Please keep me updated if it solves the issue. If not could you try to install the latest vc++ redistribuables? --> https://github.com/xavave/Mifare-Windows-Tool/discussions/63#discussioncomment-4746412

**Comment by radorodopski** [comment] 2023-01-22 21:49
I tried an old version of MWT which required libusb, but I uninstalled libusb drivers after I stopped using it and went back to the latest version.

I used v1.6.8410.22153 which I tested to work. I uninstalled it and I then installed v1.6.8422.36014 and the above issue happened. I made sure prior to installation that the MWT program was empty (except for a few dump files).

I tried deleting WinSCard.dll from the nfctools_pcsc directory and it worked to the point that there are no more DLL/linker issues. But now I am facing this:
![image](https://user-images.githubusercontent.com/2711709/213941639-97268931-5b88-4daf-9330-435173b50888.png)

If I wait more time after inserting the NFC card I get this (I reopened MWT and I detached and reattached my ACR122 reader too as it wouldn't work anymore - it stayed in a weir blocked state):
![image](https://user-images.githubusercontent.com/2711709/213941361-1306cfed-4510-4101-8831-8c6d23d2ddb3.png)

Any ideas? Now MWT is causing instabilities and can't properly read a card.
Is that caused by deleting WinSCard.dll from the nfctools_pcsc dir?
(by the way, I tested with another software right after having the above issues with MWT and I can read this card properly, the other program is "NFC Tools for Desktop")

That happens only if I answer with "Yes" to read the card again anyway, which starts mfoc-hardnested.exe (but maybe does other things too). If I answer with "No" I can read the card with MWT.
If the issue happens I also heard the "USB device disconnected" sound after mfoc-hardnested.exe is started but my reader shows a green LED and even if I remove the card there is no change. Only unplugging and plugging again the reader to USB fixes it.

Am I supposed to use MWT with WinSCard.dll from the MWT installation (so I need a fixed version) or do I use MWT with the default windows version?

**Comment by xavave** [comment] 2023-01-22 22:55
Thank you for your feedback!
It's complicated to solve as I don't have these issues on my computer. 
Maybe there is a compatibility issue due to the different C++ versions between users computers. 
As I had to recompile libusb 1.0, then libnfc based on this new libusb, and I modified the C++ code in libnfc and sometime adapt it for windows port, the issue could be from multiple places, that ms why it's complicated to solve. 
I'll try to solve the debug dll dependencies next weekend if I can find some time. 
Ideally if would like to use C# directly without wrapping libnfc , by using pcscsharp for example. 
I didn't find a perfect solution yet. 
For the issue with wiscard, it's not recommanded to include Microsoft dlls in the app. Best option would be to ask users to install VC++ redistribuables and then refer to these installed dlls from MWT without moving these dlls in nfctool_pcsc folder. 
The other point is that there are a lot of different tag readers. Even with ACR122U, different bugs can appear from one version to another.
(I have an ACR122U-A5, and I know that the A9 reacts a bit differently). I should receive some new tag readers in a few weeks and I will be able to test deeper. 
Third point: some users asked me to include more nfc drivers such as PN532-UART (that I've included in nfc.dll in this latest MWT release) but, I've noticed that when I add some new drivers, more bugs appears. 
Maybe I should provide different lib nfc.dll versions, but I would like MWT to remain easy to use. If I had to ask to people to change dll manually to adapt to their configuration,  it may be complicated. It's hard to find a compromise between ease of use and compatibility.

**Comment by radorodopski** [comment] 2023-01-22 23:23
By the way, I have the latest VC++ redistributable already so that's probably not the reason. I would recommend testing for DLL dependencies on another computer where you don't have the development tools installed (or on a VM) - that way you can catch these issues earlier on. I am grateful that you are supporting this tool - so thanks!
On this particular PC that I am using right now I prefer to not install any development tools as I am afraid one particular piece of software may stop working if I do.

Update:
Actually, I reverted back to v1.6.8410.22153 and the same issue appeared. Yesterday I didn't have this issue so no idea why this suddenly started happening. This happens less with the older version than with the latest one - no idea why (maybe just randomness).
With the older version: If I run "read tag" twice it will fail the first time and work okay on the second. Then after that it will work indefinitely (I just read my card like 30 times 😆). 
With the latest version (and WinSCard.dll deleted) it failed an caused my reader to hang for some reason (and there's no recovery from that, except to repower it) - which leads me to think you might be correct. The reader could be behaving differently due to different WinSCard.dll but I can't really prove it yet.

Anyway, for when you have time to investigate:
I noticed that when this issue happened on the output it said that there was another device using the card reader - with connection string "**acr122_pcsc**:ACS ACR122 0" with the "acr122_pcsc" driver, while mfoc-hardnested (supposedly) uses the "**pcsc**:ACS ACR122 0" connection string with the "pcsc" driver (it's there on my first screenshot in my previous comment).
Any idea which tool may be using the "acr122_pcsc" connection string? Could that be another tool that crashed and didn't clean up after itself? Or is that another windows process trying to use the device for some reason? And I don't know why that doesn't happen with the other windows app that I am also testing (NFC Tools for Desktop) which also uses PCSC to communicate to the reader (I always kill all other apps when I test MWT, just in case you might be wondering)

If that's another process (part of MWT's distribution) that potentially crashed and didn't clean up after itself - it should be easier to debug rather than chasing Windows ghost processes...

But then again, this starts after I plug in the reader via USB and some time later it recovers and the issue no longer manifests. So, it could be a Windows thing too... I won't make any assumptions, as always.

Thanks again for the support!

**Comment by xavave** [comment] 2023-01-24 10:46
* libusb was in debug dll, and caused depencies with *d.dll, it should be fixed for now
* you can now customize the libnfc settings in C:\Program Files (x86)\AVXTEC\MWT\nfctools_pcsc\libnfc.config

Could you try with this update ? https://github.com/xavave/Mifare-Windows-Tool/releases/latest

**Comment by radorodopski** [comment] 2023-01-25 22:34
The last release works fine. Thanks!

I still observe that issue with multiple processes trying to access the reader via PC/SC.
Do the connection strings I posted mean anything to you? I'd appreciate if you can share any insights

**Comment by xavave** [comment] 2023-01-25 23:05
> The last release works fine. Thanks!
> 
> I still observe that issue with multiple processes trying to access the reader via PC/SC. Do the connection strings I posted mean anything to you? I'd appreciate if you can share any insights

Hi, yes, I'm working on it, I'm trying to understand why this line doesn't seem to be called: https://github.com/nfc-tools/libnfc/blob/3df7f25f11499fa788e40c41ee7b45582262c566/libnfc/drivers/pcsc.c#L456

For the connection strings on Windows, I've added libnfc.conf in nfctools_pcsc folder and you can play with it for testing:
Here it its content:

```
# Allow device auto-detection (default: true)
# Note: if this auto-detection is disabled, user has to set manually a device
# configuration using file or environment variable
allow_autoscan = true

# Allow intrusive auto-detection (default: false)
# Warning: intrusive auto-detection can seriously disturb other devices
# This option is not recommended, user should prefer to add manually his device.
# allow_intrusive_scan = false

# Set log level (default: error)
# Valid log levels are (in order of verbosity): 0 (none), 1 (error), 2 (info), 3 (debug)
# Note: if you compiled with --enable-debug option, the default log level is "debug"
log_level = 1

# Manually set default device (no default)
# To set a default device, you must set both name and connstring for your device
# Note: if autoscan is enabled, default device will be the first device available in device list.
# device.name = "ACS ACR122 0"
# device.connstring = "acr122_pcsc:ACS ACR122 0"

```
just remove the comment # to get the line included in real configuration
the 2 last lines are working on my PC with my ACR122U

Could you tell me what you have  for ACR122U in your devices manager? (072 / 2200 too?)

<img width="451" alt="image" src="https://user-images.githubusercontent.com/3501675/214711855-1175dadf-c06c-495f-9911-ee1644751037.png">

**Comment by radorodopski** [comment] 2023-01-25 23:13
The device ID is the same. About the last two lines - they just set the default device, and I have only one device anyway.
I was wondering if there is any way to trace which process uses the other connection string?

**Comment by radorodopski** [comment] 2023-01-25 23:46
Well, if at the time of scanning another process has taken control of the reader, on line 440 the call to SCardListReaders() might return SCARD_E_READER_UNAVAILABLE (or anything other than SCARD_S_SUCCESS basically) and then it would just return out of the function and not reach line 456.
You can add a print statement before line 441 to see if my theory is right.

**Comment by xavave** [comment] 2023-01-26 02:30
I've made a nightly build, not released yet, would you like to test it? (it's here in attachment) :)
including some fixes on pcsc detection + new conf folder in nfctools_pcsc folder (you can add multiple .conf files)
+ somes tries to guess automatically keys when not found, in nfc-mfclassic.exe
[MifareWindowsTool_Test20230126.zip](https://github.com/xavave/Mifare-Windows-Tool/files/10505868/MifareWindowsTool_Test20230126.zip)

**Comment by radorodopski** [comment] 2023-01-26 05:59
I tested the above build - overall very stable. My reader didn't glitch even once, which is a first.
However, after reading the keys of my card (they're the default FFFF.... keys) there is a big waiting period, and then after reading a few block it does another waiting period. Is there a setting that changed in this build? Like the card reading speed or something?

My card is a Mifare Classic 1k (non-writable sector 0) standard card.
Overall reading time is now about 35-40 seconds, whereas before it was definitely less than 10s (so I didn't observe any noticeable delay before). For reference with the "NFC Tools for Desktop" the total time to read the card (it assumes default keys) is  less than 3s.

But in terms of stability I can't stress enough how much of an improvement this is for me.
I don't see multiple connections to the PC/SC driver, I guess your changes fixed that?
Let me know if I can help further. Thanks!

**Comment by xavave** [comment] 2023-01-26 08:28
For the bug, I've applied this fix which makes a delay, that's why reading is slower: https://groups.google.com/g/nfc-tools-issues/c/nZrtkAFYeNk

The reason why it's much slower than nfc tools for desktop is because MWT always uses mfoc hardnested to read and decrypt the tag in one operation. 

I would be faster with nfc-mfclassic in read mode with default keys. 
For ease of use of MWT, I've simplified the way it works. 

Maybe that you could try to test reading speed of your card with default keys by executing nfc-mfclassic from nfctools_PCSC folder with command line cmd.exe , you can use nfc-mfclassic -h to get information about arguments to pass

**Comment by radorodopski** [comment] 2023-01-26 08:41
Can you explain why the delay is needed?
If you got the time...

**Comment by xavave** [comment] 2023-01-26 08:51
This delay should prevent the nfc_initiator_init: Input / Output Error, which was probably the cause of the instability. I still need to investigate

**Comment by xavave** [comment] 2023-01-26 08:55
You can make reading faster in MWT by clicking on this: ![image](https://user-images.githubusercontent.com/3501675/214795022-67299091-7512-4154-8d73-c78562f83a34.png)
